// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipboardWriteImageFunc(arg1) {
  return window['go']['main']['App']['ClipboardWriteImageFunc'](arg1);
}

export function GeneratorFunc(arg1, arg2) {
  return window['go']['main']['App']['GeneratorFunc'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
