// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipboardWriteImageFunc(arg1:string):Promise<boolean>;

export function GeneratorFunc(arg1:Array<{[key: string]: any}>,arg2:Array<{[key: string]: any}>):Promise<Array<{[key: string]: any}>>;

export function Greet(arg1:string):Promise<string>;
